[tool.towncrier]
    package = "allmydata"
    package_dir = "src"
    filename = "NEWS.rst"
    directory = "newsfragments"
    start_string = ".. towncrier start line"
    title_format = "{version} ({project_date})"

    [[tool.towncrier.type]]
        directory = "incompat"
        name = "Backwards incompatible changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug fixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "installation"
        name = "Dependency/Installation changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "configuration"
        name = "Configuration changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removed"
        name = "Removed Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "other"
        name = "Other changes"
        showcontent = true
